### ISSUE TITLE
unable to login to pro

### ISSUE THREAD

**Issue by awesomescot** [travis-ci/travis.rb#269]
I'm trying to encrypt some data and when I run encrypt it says I need to login.  When I try to login I get this.  I'm sure my username and password are correct, I've tried many times.  Maybe I'm doing something wrong?

```
$ travis encrypt BLAH=blah
not logged in, please run travis login --pro

$ travis login --pro
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: awesomescot
Password for awesomescot: **************************************
Validation Failed
for a full error report, run travis report --pro

$ travis report --pro
System
Ruby:                     Ruby 2.0.0-p598
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.4.3

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-01-27 09:28:54 -0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:208:in `basic_auth'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:221:in `login'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:49:in `each_token'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:36:in `with_token'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:31:in `login'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:40:in `run'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `load'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `<main>'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Let me know if you need any more info.

**Comment by BanzaiMan** [comment]
What's the `gh` gem version?

**Comment by awesomescot** [comment]
$ gem list gh

*** LOCAL GEMS ***

gh (0.13.3)
highline (1.6.21)

**Comment by BanzaiMan** [comment]
Please try updating it to 0.14.0.

**Comment by awesomescot** [comment]
same thing
$ gem list gh

*** LOCAL GEMS ***

gh (0.14.0, 0.13.3)
highline (1.6.21)
$ travis login --pro
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: awesomescot
Password for awesomescot: ***********
Validation Failed
for a full error report, run travis report --pro
$ travis report --pro
System
Ruby:                     Ruby 2.0.0-p598
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.4.3

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-01-27 12:37:35 -0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:208:in `basic_auth'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:221:in `login'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:49:in `each_token'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:36:in `with_token'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:31:in `login'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:40:in `run'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `load'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `<main>'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.

**Comment by BanzaiMan** [comment]
Thanks for testing. It might have been due to the user data being out of sync. I've resynced it for you now (you can also do it from https://magnum.travis-ci.com/profile/awesomescot). Could you try again?

**Comment by awesomescot** [comment]
same result.  But isn't it only hitting api.github.com?  That's what login
says, but report says the endpoint is at travis-ci.com.

$ travis login --pro
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your
password anyway.

Username: awesomescot
Password for awesomescot: ***********
Validation Failed
for a full error report, run travis report --pro
$ travis report --pro
System
Ruby:                     Ruby 2.0.0-p598
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.4.3

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-01-27 13:07:49 -0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:216:in
`rescue in basic_auth'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:208:in
`basic_auth'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:221:in
`login'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:80:in
`possible_tokens'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:49:in
`each_token'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/tools/github.rb:36:in
`with_token'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:31:in
`login'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/login.rb:40:in
`run'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in
`execute'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/lib/travis/cli.rb:64:in
`run'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/gems/travis-1.7.5/bin/travis:18:in
`<top (required)>'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `load'
        from /home/scot/.rvm/gems/ruby-2.0.0-p598/bin/travis:23:in `<main>'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
        from
/home/scot/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in
`<main>'


For issues with the command line tool, please visit
https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to
https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com
.

**Comment by natyanih** [comment]
try 'travis endpoint --pro --set-default' ... solved my problem for pro

**Comment by revington** [comment]
Same here. Fixed by updating ruby gems and reinstalling

**Comment by RustComet** [comment]
This is still happening for me. I have tried re-syncing, re-installing the gem and `--set-default` 

```
An error occurred running `travis login --pro`:
    RuntimeError: Validation Failed
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:221:in `login'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:49:in `each_token'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/tools/github.rb:36:in `with_token'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/cli/login.rb:31:in `login'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/cli/login.rb:40:in `run'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/bin/travis:23:in `load'
        from /Users/isaacnorman/.rbenv/versions/2.2.3/gemsets/vent/bin/travis:23:in `<main>'
```

I have 2 factor auth on, but I still get the same error if I turn it off

**Comment by mmoayyed** [comment]
I am seeing the same error:

```bash
travis login --github-token TOKEN
successfully logged in as mmoayyed!

travis encrypt KEY=VALUE -r Org/Repo
not logged in, please run travis login --pro
```

Why do I have to login as pro?

**Comment by BanzaiMan** [comment]
@mmoayyed If your repo is private, you need to log in to pro.

**Comment by mmoayyed** [comment]
It's not private.

**Comment by BanzaiMan** [comment]
@mmoayyed Then I think this is a separate issue.

**Comment by mmoayyed** [comment]
I may know the cause, but let me quickly run this by you before I create a separate issue. What sort of access do I need to have to the public github repository? I do have push rights, but I don't have access to the Settings area of the repo. Is that required for this task? 

I have done this successfully in the past for other projects where the only difference has been that I had access to modify the Settings. Is that relevant?

**Comment by jcasner** [comment]
I was having the same issue. I ended up resolving it by deleting the `temporary token for pro` at https://github.com/settings/tokens. Hope this helps someone else...

**Comment by alexanderkjeldaas** [comment]
why is this issue closed?

**Comment by damianobarbati** [comment]
I totally don't get it: how are we supposed to login?
With personal github username/pwd? Or person username/ad-hoc token?
or with company's travis account username/pwd? Or company username/ad-hoc token?
I'm trying everything with no success. @alexanderkjeldaas do you know how to login?

**Comment by bhansa** [comment]
Getting similar error:
```
$ travis report --pro
System
Ruby:                     Ruby 2.4.5-p335
Operating System:         Windows
RubyGems:                 RubyGems 3.1.4

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-10-03 11:48:23 +0530

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (default, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Unknown error
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:212:in `rescue in basic_auth'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from C:/Ruby24-x64/bin/travis:23:in `load'
        from C:/Ruby24-x64/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by zygimantus** [comment]
> RuntimeError: Unknown error

@bhansa did you resolved this issue? I have the same.

**Comment by BanzaiMan** [comment]
@bhansa @zygimantus It seems that GitHub is responding with something that we do not expect. Can you run the command with `--explode`, as well as `--debug` `--debug-http`, and report the result?  Thanks.

    travis login --debug --debug-http --explode

**Comment by zygimantus** [comment]
@BanzaiMan thanks, seems that this error is related to Ruby certificates?

C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (Faraday::SSLError)
        70: from C:/Ruby27-x64/bin/travis:23:in `<main>'
        69: from C:/Ruby27-x64/bin/travis:23:in `load'
        68: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        67: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        66: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
        65: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
        64: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
        63: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
        62: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
        61: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
        60: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
        59: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:210:in `basic_auth'
        58: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:236:in `with_otp'
        57: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:217:in `block in login'
        56: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/tools/github.rb:225:in `create_token'
        55: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        54: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        53: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        52: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        51: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        50: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        49: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        48: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        47: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `post'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/remote.rb:99:in `post'
        45: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        44: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        43: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        42: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        41: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        40: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        39: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        38: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        37: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `request'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/remote.rb:88:in `request'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `http'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `instrument'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli/api_command.rb:141:in `block in load_gh'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/travis-1.10.0/lib/travis/cli/command.rb:267:in `time'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `block in instrument'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `block in http'
        29: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        28: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/token_check.rb:28:in `http'
        26: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        25: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        24: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        23: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        22: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `http'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/gh-0.18.0/lib/gh/remote.rb:81:in `http'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/request/authorization.rb:51:in `call'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/request/retry.rb:148:in `call'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/instrumentation.rb:31:in `call'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/instrumentation.rb:32:in `block in call'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:137:in `request_with_wrapped_block'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:152:in `request_via_request_method'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:932:in `start'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': GH request failed (GH::Error)
verb:               :post
url:                /authorizations
headers:            {"User-Agent"=>"GH/0.18.0", "Accept"=>"application/vnd.github.v3+json", "Accept-Charset"=>"utf-8"}
error:              Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
payload:            {"scopes":["read:org","user:email","repo_deployment","repo:status","write:repo_hook"],"note":"temporary token to identify with the travis command line client against https://api.travis-ci.org/"}

**Comment by BanzaiMan** [comment]
@zygimantus Indeed, it does, and I don't know how to fix that.

Can you connect to other sites over HTTPS with your Ruby? I feel that the issue is with your Ruby installation, unfortunately.

**Comment by oya163** [comment]
I was also not able to login using `travis login --com`, but I am able to login using `travis login --com --github-token`

**Comment by dongnold** [comment]
The same. I was also not able to login using travis login --com. But using travis login --com --github-token works fine.

**Comment by oStritze** [comment]
This is still somewhat buggy, i was not able to authenticate with `travis login --pro --com` in any way, but generating a token on github with the necessary scopes and using `--github-token` worked.

I got a 404 Not found:
`** GitHub API: POST /authorizations
Traceback (most recent call last):
	59: from /usr/local/bin/travis:23:in `<main>'
	58: from /usr/local/bin/travis:23:in `load'
	57: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
	56: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
	55: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
	54: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
	53: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
	52: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
	51: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
	50: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
	49: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
	48: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:210:in `basic_auth'
	47: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:236:in `with_otp'
	46: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:217:in `block in login'
	45: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:225:in `create_token'
	44: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	43: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	42: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	41: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	40: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	39: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	38: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	37: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	36: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	35: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:99:in `post'
	34: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	33: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	32: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	31: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	30: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	29: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	28: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	27: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	26: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	25: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:88:in `request'
	24: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `http'
	23: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `instrument'
	22: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/api_command.rb:141:in `block in load_gh'
	21: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/command.rb:267:in `time'
	20: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `block in instrument'
	19: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `block in http'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	16: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/token_check.rb:28:in `http'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	 8: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:81:in `http'
	 7: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	 6: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	 5: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/request/authorization.rb:51:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/request/retry.rb:148:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
	 2: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'
	 1: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:19:in `block in call'
/Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/response/raise_error.rb:22:in `on_complete': the server responded with status 404 (Faraday::ResourceNotFound)
	59: from /usr/local/bin/travis:23:in `<main>'
	58: from /usr/local/bin/travis:23:in `load'
	57: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
	56: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
	55: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
	54: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
	53: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
	52: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
	51: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
	50: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
	49: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
	48: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:210:in `basic_auth'
	47: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:236:in `with_otp'
	46: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:217:in `block in login'
	45: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/tools/github.rb:225:in `create_token'
	44: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	43: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	42: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	41: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	40: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	39: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	38: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	37: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	36: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
	35: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:99:in `post'
	34: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	33: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	32: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	31: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	30: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	29: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	28: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	27: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	26: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
	25: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:88:in `request'
	24: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `http'
	23: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `instrument'
	22: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/api_command.rb:141:in `block in load_gh'
	21: from /Library/Ruby/Gems/2.6.0/gems/travis-1.10.0/lib/travis/cli/command.rb:267:in `time'
	20: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:32:in `block in instrument'
	19: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/instrumentation.rb:16:in `block in http'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	16: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/token_check.rb:28:in `http'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `http'
	 8: from /Library/Ruby/Gems/2.6.0/gems/gh-0.18.0/lib/gh/remote.rb:81:in `http'
	 7: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	 6: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	 5: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/request/authorization.rb:51:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/request/retry.rb:148:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
	 2: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'
	 1: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:19:in `block in call'
/Library/Ruby/Gems/2.6.0/gems/faraday-1.7.1/lib/faraday/response/raise_error.rb:22:in `on_complete': GH request failed (GH::Er`
