### ISSUE TITLE
Log-related commands and methods broken (round 2?)

### ISSUE THREAD

**Issue by matthewmorley** [travis-ci/travis.rb#493]
See https://github.com/travis-ci/travis.rb/issues/488, essentially the same issue.

Working around it locally for now by using:
`body = job.session.get_raw("jobs/#{job.id}/log", nil, 'Accept' => 'text/plain')`
instead of calling
`job.log.body`

This broke sometime yesterday for me, but it possible I made the jump from 1.8.6 to 1.8.8, but it also seems like neither work at the moment for log related requests, via the cli or via ruby using the gem.

ref in travis-api PR: https://github.com/travis-ci/travis-api/pull/427#issuecomment-290111190

@meatballhat

**Comment by matthewmorley** [comment]
`travis report --pro
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Mac OS X 10.12.3
RubyGems:                 RubyGems 2.6.10

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-03-29 10:54:26 -0400

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "validuser"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /Users/validuser/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/bin/travis:22:in `load'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/bin/travis:22:in `<main>'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/validuser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.`

**Comment by BenKanouse** [comment]
I am still seeing the same issue described here: https://github.com/travis-ci/travis.rb/issues/488

 It seems that all instances of Travis::Client::Job are returning nil for the `log` and `log_id` method. So naturally any method I chain off of that method returns an undefined method for nil error.

**Comment by jamesiarmes** [comment]
Seeing this issue as well when trying to reload a job object:

```
.../lib/travis/client/session.rb:123:in `reset': undefined method `attributes' for nil:NilClass (NoMethodError)
```

**Comment by jamesiarmes** [comment]
https://gist.github.com/jamesiarmes/fa6ebdc54c072724a24e54131d62323b works around the issue for me, but since the the `log` and `log_id` are still `nil`, it doesn't resolve the actual issue.

**Comment by eupharis** [comment]
same for me :(

**Comment by rmoriz** [comment]
same for me (ruby 2.3.3)

```

An error occurred running `travis restart --pro`:
    NoMethodError: undefined method `attributes' for nil:NilClass
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:122:in `reset'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:148:in `block in reload'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:148:in `each'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:148:in `reload'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/methods.rb:78:in `restart'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/restartable.rb:11:in `restart'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/restart.rb:12:in `run'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/bin/travis:22:in `load'
        from /Users/rmoriz/.asdf/installs/ruby/2.3.3/bin/travis:22:in `<main>'

```

**Comment by meatballhat** [comment]
👋 Hi everyone, sorry about the delay.  The issue with `log` and `log_id` being `nil` should have been resolved shortly after this issue was first raised.  In the case of @rmoriz' comment, can you provide some specifics about which log(s) you were trying to view so that I can check if there's a data integrity issue?

**Comment by eupharis** [comment]
@meatballhat  public `travis-ci.org` repos do work for me:
`travis logs -r travis-ci/travis-api 5179`

I tried 6 different private repos in a github org and they all fail in the same way when I try to view from the command line with:
`travis logs -r REPONAME`
likewise with 
`travis logs -r REPONAME BUILDNO`

Here is report --pro for a failure:
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-04-28 10:58:55 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "eupharis"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```
can send you a private message with the specific repo names if that'd be helpful.

**Comment by liorrozen** [comment]
I am still getting the same errors as #488 for all private repos in my org. Public repos seem to be working though.

```System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Mac OS X 10.12.4
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-04-29 01:17:13 +0300

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "liorrozen"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `body' for nil:NilClass
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/travis:23:in `load'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/travis:23:in `<main>'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/liorr/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This has been fixed!
