### ISSUE TITLE
`travis monitor` fails with AssetNotFound in 1.10.0

### ISSUE THREAD

**Issue by theburge** [travis-ci/travis.rb#776]
On macOS 10.15.7, installed from homebrew, I see this:

```
% travis monitor                                                  Traceback (most recent call last):
        18: from /usr/local/Cellar/travis/1.10.0/libexec/bin/travis:23:in `<main>'
        17: from /usr/local/Cellar/travis/1.10.0/libexec/bin/travis:23:in `load'
        16: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        15: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/cli.rb:62:in `run'
        14: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/cli.rb:69:in `command'
        13: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/cli.rb:69:in `const_get'
        12: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        11: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        10: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/cli/monitor.rb:2:in `<top (required)>'
         9: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         8: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         7: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:6:in `<top (required)>'
         6: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:7:in `<module:Travis>'
         5: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:8:in `<module:Tools>'
         4: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:26:in `<module:Notification>'
         3: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:27:in `<class:Dummy>'
         2: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/assets.rb:9:in `asset_path'
         1: from /usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/assets.rb:9:in `tap'
/usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/assets.rb:10:in `block in asset_path': Travis CI.app/Contents/MacOS/Travis CI (Travis::Client::AssetNotFound)
```

I can also reproduce using gem to install with the system Ruby (2.6.0).

**Comment by AdrieanKhisbe** [comment]
Was facing the same issue.

Should be fixed by #770 that was not released yet.

(applying it locally by monkey patching `/usr/local/Cellar/travis/1.10.0/libexec/gems/travis-1.10.0/lib/travis/tools/notification.rb:27` removing dummy asset solves the issue on my macos)

**Comment by whiskey** [comment]
Hey hey. It's June now and we still see this issue. Is there any hint when the CLI updates?
